#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : taglib
Version  : 1.11.1
Release  : 2
URL      : http://taglib.org/releases/taglib-1.11.1.tar.gz
Source0  : http://taglib.org/releases/taglib-1.11.1.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : LGPL-2.1 MPL-1.1
Requires: taglib-bin
Requires: taglib-lib
Requires: taglib-license
BuildRequires : boost-dev
BuildRequires : buildreq-cmake
BuildRequires : zlib-dev
Patch1: cve-2017-12678.patch

%description
Run "make docs" in the parent directory to generate the TagLib API documentation.

%package bin
Summary: bin components for the taglib package.
Group: Binaries
Requires: taglib-license

%description bin
bin components for the taglib package.


%package dev
Summary: dev components for the taglib package.
Group: Development
Requires: taglib-lib
Requires: taglib-bin
Provides: taglib-devel

%description dev
dev components for the taglib package.


%package lib
Summary: lib components for the taglib package.
Group: Libraries
Requires: taglib-license

%description lib
lib components for the taglib package.


%package license
Summary: license components for the taglib package.
Group: Default

%description license
license components for the taglib package.


%prep
%setup -q -n taglib-1.11.1
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1534703763
mkdir clr-build
pushd clr-build
export CFLAGS="$CFLAGS -fstack-protector-strong -mzero-caller-saved-regs=used "
export FCFLAGS="$CFLAGS -fstack-protector-strong -mzero-caller-saved-regs=used "
export FFLAGS="$CFLAGS -fstack-protector-strong -mzero-caller-saved-regs=used "
export CXXFLAGS="$CXXFLAGS -fstack-protector-strong -mzero-caller-saved-regs=used "
%cmake ..
make  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1534703763
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/taglib
cp COPYING.LGPL %{buildroot}/usr/share/doc/taglib/COPYING.LGPL
cp COPYING.MPL %{buildroot}/usr/share/doc/taglib/COPYING.MPL
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/taglib-config

%files dev
%defattr(-,root,root,-)
/usr/include/taglib/aifffile.h
/usr/include/taglib/aiffproperties.h
/usr/include/taglib/apefile.h
/usr/include/taglib/apefooter.h
/usr/include/taglib/apeitem.h
/usr/include/taglib/apeproperties.h
/usr/include/taglib/apetag.h
/usr/include/taglib/asfattribute.h
/usr/include/taglib/asffile.h
/usr/include/taglib/asfpicture.h
/usr/include/taglib/asfproperties.h
/usr/include/taglib/asftag.h
/usr/include/taglib/attachedpictureframe.h
/usr/include/taglib/audioproperties.h
/usr/include/taglib/chapterframe.h
/usr/include/taglib/commentsframe.h
/usr/include/taglib/eventtimingcodesframe.h
/usr/include/taglib/fileref.h
/usr/include/taglib/flacfile.h
/usr/include/taglib/flacmetadatablock.h
/usr/include/taglib/flacpicture.h
/usr/include/taglib/flacproperties.h
/usr/include/taglib/generalencapsulatedobjectframe.h
/usr/include/taglib/id3v1genres.h
/usr/include/taglib/id3v1tag.h
/usr/include/taglib/id3v2extendedheader.h
/usr/include/taglib/id3v2footer.h
/usr/include/taglib/id3v2frame.h
/usr/include/taglib/id3v2framefactory.h
/usr/include/taglib/id3v2header.h
/usr/include/taglib/id3v2synchdata.h
/usr/include/taglib/id3v2tag.h
/usr/include/taglib/infotag.h
/usr/include/taglib/itfile.h
/usr/include/taglib/itproperties.h
/usr/include/taglib/modfile.h
/usr/include/taglib/modfilebase.h
/usr/include/taglib/modproperties.h
/usr/include/taglib/modtag.h
/usr/include/taglib/mp4atom.h
/usr/include/taglib/mp4coverart.h
/usr/include/taglib/mp4file.h
/usr/include/taglib/mp4item.h
/usr/include/taglib/mp4properties.h
/usr/include/taglib/mp4tag.h
/usr/include/taglib/mpcfile.h
/usr/include/taglib/mpcproperties.h
/usr/include/taglib/mpegfile.h
/usr/include/taglib/mpegheader.h
/usr/include/taglib/mpegproperties.h
/usr/include/taglib/oggfile.h
/usr/include/taglib/oggflacfile.h
/usr/include/taglib/oggpage.h
/usr/include/taglib/oggpageheader.h
/usr/include/taglib/opusfile.h
/usr/include/taglib/opusproperties.h
/usr/include/taglib/ownershipframe.h
/usr/include/taglib/podcastframe.h
/usr/include/taglib/popularimeterframe.h
/usr/include/taglib/privateframe.h
/usr/include/taglib/relativevolumeframe.h
/usr/include/taglib/rifffile.h
/usr/include/taglib/s3mfile.h
/usr/include/taglib/s3mproperties.h
/usr/include/taglib/speexfile.h
/usr/include/taglib/speexproperties.h
/usr/include/taglib/synchronizedlyricsframe.h
/usr/include/taglib/tableofcontentsframe.h
/usr/include/taglib/tag.h
/usr/include/taglib/tag_c.h
/usr/include/taglib/taglib.h
/usr/include/taglib/taglib_config.h
/usr/include/taglib/taglib_export.h
/usr/include/taglib/tbytevector.h
/usr/include/taglib/tbytevectorlist.h
/usr/include/taglib/tbytevectorstream.h
/usr/include/taglib/tdebuglistener.h
/usr/include/taglib/textidentificationframe.h
/usr/include/taglib/tfile.h
/usr/include/taglib/tfilestream.h
/usr/include/taglib/tiostream.h
/usr/include/taglib/tlist.h
/usr/include/taglib/tlist.tcc
/usr/include/taglib/tmap.h
/usr/include/taglib/tmap.tcc
/usr/include/taglib/tpropertymap.h
/usr/include/taglib/trefcounter.h
/usr/include/taglib/trueaudiofile.h
/usr/include/taglib/trueaudioproperties.h
/usr/include/taglib/tstring.h
/usr/include/taglib/tstringlist.h
/usr/include/taglib/uniquefileidentifierframe.h
/usr/include/taglib/unknownframe.h
/usr/include/taglib/unsynchronizedlyricsframe.h
/usr/include/taglib/urllinkframe.h
/usr/include/taglib/vorbisfile.h
/usr/include/taglib/vorbisproperties.h
/usr/include/taglib/wavfile.h
/usr/include/taglib/wavpackfile.h
/usr/include/taglib/wavpackproperties.h
/usr/include/taglib/wavproperties.h
/usr/include/taglib/xingheader.h
/usr/include/taglib/xiphcomment.h
/usr/include/taglib/xmfile.h
/usr/include/taglib/xmproperties.h
/usr/lib64/libtag.so
/usr/lib64/libtag_c.so
/usr/lib64/pkgconfig/taglib.pc
/usr/lib64/pkgconfig/taglib_c.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libtag.so.1
/usr/lib64/libtag.so.1.17.0
/usr/lib64/libtag_c.so.0
/usr/lib64/libtag_c.so.0.0.0

%files license
%defattr(-,root,root,-)
/usr/share/doc/taglib/COPYING.LGPL
/usr/share/doc/taglib/COPYING.MPL
